$(document).ready(function(){
    $(".img").click(function(){
        $(".img").hide();
        $(".showing").show();
    });
    $(".showing").click(function(){
        $(".showing").hide();
        $(".img").show();
    });
